dist: xenial
language: node_js
addons:
  postgresql: "10"
apt:
  packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql-10
env:
  global:
    - DB_HOST=localhost
    - DB_USER=root
    - DB_PASS=root
    - DB_NAME=loelottest
    - DB_PORT=5432
    - DB_DIALECT=postgres
    - NODE_ENV=test
before_install:
  - psql -c 'CREATE DATABASE loelottest;' -U postgres
  