dist: xenial
language: node_js
node_js:
  - "10"
addons:
  postgresql: "10"
apt:
  packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql-10
env:
  global:
    - DB_HOST=localhost
    - DB_USER=root
    - DB_PASS=root
    - DB_NAME=loelottest
    - DB_PORT=5432
    - DB_DIALECT=postgres
    - NODE_ENV=test
    - FACEBOOK_APP_ID=xxx
    - FACEBOOK_APP_SECRET=xxx
before_install:
  - psql -c 'CREATE DATABASE loelottest;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD 'root';" -U postgres
  - psql -c 'CREATE EXTENSION "uuid-ossp";' -U postgres -d loelottest
  